const cinnostiPololeti = [
  {
    name: "Okna dole, osprchovat kytky, vyprat záclony",
    time: 45,
    completed: false,
    who: "Matěj",
    tyden: false,
  },
  {
    name: "Okna nahoře, vyprat záclony",
    time: 45,
    completed: false,
    who: "Máma",
    tyden: false,
  },
  {
    name: "Okna koupelna, chodba",
    time: 30,
    completed: false,
    who: "Matěj",
    tyden: false,
  },
  {
    name: "Okna veranda, z kuchyně na verandu",
    time: 30,
    completed: false,
    who: "Máma",
    tyden: false,
  },
  {
    name: "Dveře uvnitř (celkem 6)",
    time: 60,
    completed: false,
    who: "Matěj",
    tyden: false,
  },
  {
    name: "Dveře ven, na dvůr a do garáže",
    time: 30,
    completed: false,
    who: "Matěj",
    tyden: false,
  },
  {
    name: "Radiátory (celkem 6)",
    time: 60,
    completed: false,
    who: "Táta",
    tyden: false,
  },
  {
    name: "Svítidla (celkem cca 12)",
    time: 60,
    completed: false,
    who: "Kuba",
    tyden: false,
  },
  {
    name: "Obrazy, vypínače a ostatní na stěnách",
    time: 30,
    completed: true,
    who: "Kuba",
    tyden: false,
  },
  {
    name: "Zrcadla kromě koupelny",
    time: 45,
    completed: false,
    who: "Matěj",
    tyden: false,
  },
  {
    name: "Trouba",
    time: 30,
    completed: false,
    who: "Táta",
    tyden: false,
  },
  {
    name: "Skříňky v kuchyni vlevo zevnitř, zvenku, shora",
    time: 60,
    completed: false,
    who: "Kuba",
    tyden: false,
  },
  {
    name: "Skříňky v kuchyni vpravo zevnitř, zvenku, shora, osprchovat kytky",
    time: 60,
    completed: false,
    who: "Kuba",
    tyden: false,
  },
  {
    name:
      "Skříně v obýváku zevnitř, zvenku, shora (bez vyndávání knih), osprchovat kytky",
    time: 30,
    completed: false,
    who: "Matěj",
    tyden: false,
  },
  {
    name: "Vyčistit prostor za pračkou, za ledničkou",
    time: 20,
    completed: false,
    who: "Táta",
    tyden: false,
  },
  {
    name: "Propláchnout pračku octem",
    time: 0,
    completed: false,
    who: "Táta",
    tyden: false,
  },
  {
    name: "Čistit odpady",
    time: 30,
    completed: false,
    who: "Táta",
    tyden: false,
  },
  {
    name:
      "Kachlíky v koupelně, na záchodě, zrcadlo v koupelně shora, radiátor v koupelně",
    time: 60,
    completed: false,
    who: "Kuba",
    tyden: false,
  },
  {
    name: "Skříňka v koupelně zevnitř, zvenku",
    time: 30,
    completed: true,
    who: "Máma",
    tyden: false,
  },
  {
    name: "Sprchový kout",
    time: 30,
    completed: false,
    who: "Táta",
    tyden: false,
  },
  {
    name: "Všechny kohoutky a odtoky octem",
    time: 20,
    completed: false,
    who: "Táta",
    tyden: false,
  },
  {
    name: "Botníky v chodbě vymýt",
    time: 30,
    completed: false,
    who: "Matěj",
    tyden: false,
  },
  {
    name: "Vytřídit a uspořádat oblečení - máma",
    time: 60,
    completed: true,
    who: "Máma",
    tyden: false,
  },
  {
    name: "Vytřídit a uspořádat oblečení - táta",
    time: 60,
    completed: false,
    who: "Táta",
    tyden: false,
  },
  {
    name: "Vytřídit a uspořádat oblečení - Kuba",
    time: 60,
    completed: false,
    who: "Kuba",
    tyden: false,
  },
  {
    name: "Vytřídit a uspořádat své věci kromě oblečení - Kuba",
    time: 60,
    completed: true,
    who: "Kuba",
    tyden: false,
  },
  {
    name: "Vytřídit a uspořádat oblečení - Matěj",
    time: 60,
    completed: false,
    who: "Matěj",
    tyden: false,
  },
  {
    name: "Vytřídit a uspořádat své věci kromě oblečení - Matěj",
    time: 60,
    completed: true,
    who: "Matěj",
    tyden: false,
  },
  {
    name: "Lékárna – vyřadit prošlé léky, dokoupit",
    time: 30,
    completed: false,
    who: "Máma",
    tyden: false,
  },
  {
    name: "Odnést prošlé léky a vybité baterie",
    time: 30,
    completed: false,
    who: "Táta",
    tyden: false,
  },
  {
    name: "Probrat nádobí, vyhodit staré, udělat nákupní seznam",
    time: 30,
    completed: false,
    who: "Máma",
    tyden: false,
  },
  {
    name: "Sklep – srovnat, vyházet zbytečné věci",
    time: 60,
    completed: false,
    who: "Máma",
    tyden: false,
  },
  {
    name: "Udělat pořádek v garáži-1.polovina",
    time: 60,
    completed: false,
    who: "Táta",
    tyden: false,
  },
  {
    name: "Udělat pořádek v garáži-2.polovina",
    time: 60,
    completed: false,
    who: "Táta",
    tyden: false,
  },
  {
    name: "Přesadit kytky",
    time: 30,
    completed: false,
    who: "Matěj",
    tyden: false,
  },
  {
    name: "Vyprat a znovu navléct textilie v obýváku",
    time: 30,
    completed: false,
    who: "Máma",
    tyden: false,
  },
  {
    name: "Velká skříň v chodbičce: prohlédnout, uspořádat, zařadit papíry",
    time: 60,
    completed: false,
    who: "Máma",
    tyden: false,
  },
  {
    name: "Stůl na verandě: důkladně umýt, probrat zásuvky",
    time: 60,
    completed: false,
    who: "Kuba",
    tyden: false,
  },
  {
    name:
      "Základní dom. potřeby (sirky, svíčky, párátka, gumičky, nůžky...) -  udělat seznam, co chybí",
    time: 10,
    completed: false,
    who: "Máma",
    tyden: false,
  },
  {
    name: "Vyžehlit a znovu pověsit záclony dole, nahoře",
    time: 60,
    completed: false,
    who: "Máma",
    tyden: false,
  },
  {
    name:
      "Vyvézt odpad do sběrného dvora včetně oblečení a hraček na charitu a kovového odpadu",
    time: 60,
    completed: false,
    who: "Táta",
    tyden: false,
  },
  {
    name: "Zábradlí na schodech",
    time: 20,
    completed: false,
    who: "Matěj",
    tyden: false,
  },
  {
    name: "Podlaha v kuchyni rejžákem",
    time: 60,
    completed: true,
    who: "Máma",
    tyden: false,
  },
];

export default cinnostiPololeti;
