const cinnostiTyden = [
  {
    name: "Kuchyň a veranda",
    time: 60,
    completed: false,
    who: undefined,
    tyden: true,
  },
  {
    name: "Odmrazit lednici",
    time: 60,
    completed: false,
    who: undefined,
    tyden: true,
  },
  {
    name: "Uklidit krámy v obýváku",
    time: 10,
    completed: false,
    who: undefined,
    tyden: true,
  },
  {
    name: "Prach v obýváku",
    time: 10,
    completed: false,
    who: undefined,
    tyden: true,
  },
  {
    name: "Podlaha v obýváku",
    time: 20,
    completed: false,
    who: undefined,
    tyden: true,
  },
  { name: "Koupelna", time: 20, completed: false, who: undefined, tyden: true },
  { name: "Záchod", time: 10, completed: false, who: undefined, tyden: true },
  {
    name: "Prach v chodbě a ložnici",
    time: 10,
    completed: false,
    who: undefined,
    tyden: true,
  },
  {
    name: "Podlaha v chodbě",
    time: 20,
    completed: false,
    who: undefined,
    tyden: true,
  },
  {
    name: "Podlaha v kuchyni",
    time: 10,
    completed: false,
    who: undefined,
    tyden: true,
  },
  {
    name: "Za dveřmi a parapety zvenku",
    time: 10,
    completed: false,
    who: undefined,
    tyden: true,
  },
  {
    name: "Pavučiny všude",
    time: 20,
    completed: false,
    who: undefined,
    tyden: true,
  },
  {
    name: "Odnést plasty, sklo a papír",
    time: 20,
    completed: false,
    who: undefined,
    tyden: true,
  },
  {
    name: "Prach a podlaha na verandě",
    time: 10,
    completed: false,
    who: undefined,
    tyden: true,
  },
  {
    name: "Objednat jídlo",
    time: 40,
    completed: false,
    who: undefined,
    tyden: true,
  },
  {
    name: "Převléct postele v ložnici",
    time: 30,
    completed: false,
    who: undefined,
    tyden: true,
  },
  {
    name: "Převléct postel u Kuby",
    time: 20,
    completed: false,
    who: undefined,
    tyden: true,
  },
  {
    name: "Převléct postel u Matěje",
    time: 20,
    completed: false,
    who: undefined,
    tyden: true,
  },
  {
    name: "Uklidit jídlo",
    time: 20,
    completed: false,
    who: undefined,
    tyden: true,
  },
  {
    name: "Uklidit krámy z chodby",
    time: 10,
    completed: false,
    who: undefined,
    tyden: true,
  },
  {
    name: "Kubův pokoj",
    time: 20,
    completed: false,
    who: undefined,
    tyden: true,
  },
  {
    name: "Matějův pokoj",
    time: 20,
    completed: false,
    who: undefined,
    tyden: true,
  },
  {
    name: "Podlaha v ložnici a chodbičce",
    time: 10,
    completed: false,
    who: undefined,
    tyden: true,
  },
  {
    name: "Schody do sklepa",
    time: 15,
    completed: false,
    who: undefined,
    tyden: true,
  },
  {
    name: "Prát, věšet 3 pračky",
    time: 30,
    completed: false,
    who: undefined,
    tyden: true,
  },
  {
    name: "Žehlit, uklízet prádlo",
    time: 45,
    completed: false,
    who: undefined,
    tyden: true,
  },
  {
    name: "Vařit oběd",
    time: 45,
    completed: false,
    who: undefined,
    tyden: true,
  },
  {
    name: "Vařit večeři",
    time: 45,
    completed: false,
    who: undefined,
    tyden: true,
  },
  {
    name: "Zalít kytky",
    time: 10,
    completed: false,
    who: undefined,
    tyden: true,
  },
];

export default cinnostiTyden;
